### ISSUE TITLE
help

### ISSUE THREAD

**Issue by zyloxfps** [TMMarkus/AkinaRP-Clothes-Tool#11]
where do i open it

**Comment by TMMarkus** [comment]
Simply download the EXE from the 'Releases' section and run it. If you want to open the project to modify the code, download the repository, either using GIT or directly from the 'Code' button and 'Download ZIP.' Then, run the 'AkinaRPTool.sln' file using Visual Studio (I recommend version 2022).

Sorry for late response :(
